### ISSUE TITLE
UVCControl V2

### ISSUE THREAD

**Issue by positlabs** [joelpurra/uvcc#1]
Just a heads up, UVCControl V2 is coming soon :)

There is a bunch of new stuff already on master, but not released to npm yet

https://github.com/makenai/node-uvc-control

**Comment by joelpurra** [comment]
Sounds good! I'll keep this issue open as a reminder, but there's no set timeline at the moment. Thank you for the heads up =)

**Comment by joelpurra** [comment]
@positlabs: thanks for the improvements! I have updated to https://github.com/makenai/node-uvc-control/commit/master (https://github.com/makenai/node-uvc-control/commit/ca1e2c963e98b309ad3b65c5fc538f052ea5fd64).

Found some issues and fixed them in my own fork, which is now in use by `uvcc` v2.0.0. Please see pull request in `uvc-control`. I'd be happy if they were merged =)

- https://github.com/joelpurra/node-uvc-control/tree/v2
- https://github.com/makenai/node-uvc-control/pull/66

Closing this issue in `uvcc` in favor of the pull request in `uvc-control`.
