### ISSUE TITLE
The new version of uvcc doesn't terminate

### ISSUE THREAD

**Issue by wookayin** [joelpurra/uvcc#22]
uvcc v5.0.1
node v17.0.1
MacOS 12.0

*Any* command of uvcc does not terminate right after printing something.

e.g.
```
> uvcc get absolute_zoom
150
```

It prints something, but the process doesn't terminate.
\

**Comment by wookayin** [comment]
Maybe duplicate of #20

**Comment by joelpurra** [comment]
@wookayin: yes, it's  duplicate.
