### ISSUE TITLE
Get error trying to do `uvcc set absolute_exposure_time` on C920 camera

### ISSUE THREAD

**Issue by galak** [joelpurra/uvcc#6]
kumar-macair:node-uvc-control galak$ uvcc set absolute_exposure_time 500
Error: Could not find a settable control named "absolute_exposure_time".
    at CameraHelper.setValues (/usr/local/lib/node_modules/uvcc/dist/camera-helper.js:54:19)
    at async CommandHandlers.execute (/usr/local/lib/node_modules/uvcc/dist/command-handlers.js:43:24)
    at async CommandManager.execute (/usr/local/lib/node_modules/uvcc/dist/command-manager.js:71:28)
    at async mainAsync (/usr/local/lib/node_modules/uvcc/dist/index.js:73:9)

**Comment by joelpurra** [comment]
@galak: `absolute_exposure_time` is not always a _settable_ control. This depends on both other settings, such as auto-exposure, and general (hardware) support for the camera in question.

`uvcc` checks with `uvc-control` if the control is settable before attempting to set values, and throws if it is not.

- https://github.com/joelpurra/uvcc/blob/62c1e72b6725d4b07e38b5f6a4ce2b8ffbf3e428/src/camera-control-helper.ts#L83-L91
- https://github.com/joelpurra/uvcc/blob/62c1e72b6725d4b07e38b5f6a4ce2b8ffbf3e428/src/camera-helper.ts#L69-L71

From [`UVC 1.5 Class specification.pdf`](https://www.usb.org/documents?search=uvc):

> **4.2.2.1.4 Exposure Time (Absolute) Control**  
> [---] Note that the manual exposure control is further limited by the frame interval, which always has higher precedence. If the frame interval is changed to a value below the current value of the Exposure Control, the Exposure Control value will automatically be changed. The default Exposure Control value will be the current frame interval until an explicit exposure value is chosen. When the Auto-Exposure Mode control is in Auto mode or Aperture Priority mode attempts to programmatically set this control shall result in a protocol STALL and an error code of bRequestErrorCode = “Wrong state”. [---]  
> Optional Requests: `SET_CUR`

While I also have a C920 camera, I haven't experimented much with the `absolute_exposure_time` control specifically. Did you find a combination of settings where it is possible to set it?

**Comment by galak** [comment]
I've tried under linux with `v4l2-ctl` I was able to set `exposure_absolute` which I'm guessing is the same setting.

Here's a dump from `v4l2-ctl`:

```
                     brightness 0x00980900 (int)    : min=0 max=255 step=1 default=128 value=128
                       contrast 0x00980901 (int)    : min=0 max=255 step=1 default=128 value=128
                     saturation 0x00980902 (int)    : min=0 max=255 step=1 default=128 value=128
 white_balance_temperature_auto 0x0098090c (bool)   : default=1 value=1
                           gain 0x00980913 (int)    : min=0 max=255 step=1 default=0 value=0
           power_line_frequency 0x00980918 (menu)   : min=0 max=2 default=2 value=2
      white_balance_temperature 0x0098091a (int)    : min=2000 max=6500 step=1 default=4000 value=4000 flags=inactive
                      sharpness 0x0098091b (int)    : min=0 max=255 step=1 default=128 value=128
         backlight_compensation 0x0098091c (int)    : min=0 max=1 step=1 default=0 value=0
                  exposure_auto 0x009a0901 (menu)   : min=0 max=3 default=3 value=3
              exposure_absolute 0x009a0902 (int)    : min=3 max=2047 step=1 default=250 value=250 flags=inactive
         exposure_auto_priority 0x009a0903 (bool)   : default=0 value=1
                   pan_absolute 0x009a0908 (int)    : min=-36000 max=36000 step=3600 default=0 value=0
                  tilt_absolute 0x009a0909 (int)    : min=-36000 max=36000 step=3600 default=0 value=0
                 focus_absolute 0x009a090a (int)    : min=0 max=250 step=5 default=0 value=0 flags=inactive
                     focus_auto 0x009a090c (bool)   : default=1 value=1
                  zoom_absolute 0x009a090d (int)    : min=100 max=500 step=1 default=100 value=100            
```

**Comment by joelpurra** [comment]
@galak: are you sure the setting was applied? I would guess you tried to set `exposure_absolute` to 500, like in your first `uvcc` example, but in your `v4l2-ctl` output it has a value of `250`, which is also the default.

**Comment by galak** [comment]
Mostly I'm trying to figure out how to explicitly set the exposure.

to do that I can do:

Set exposure to manual:
`v4l2-ctl -d /dev/video1 -c exposure_auto=1`

Set exposure_absolute:
`v4l2-ctl -d /dev/video1 -c exposure_absolute=600`

Read back exposure:
`v4l2-ctl -d /dev/video1 -C exposure_absolute`
exposure_absolute: 624

So trying to figure out how to do that with uvcc.

**Comment by galak** [comment]
So if I remove the `settableControlNames.includes` check then I'm able to modify `absolute_exposure_time` and see a difference.

**Comment by galak** [comment]
> I'm not to familiar with node/npm. How would you suggest I install v2.0.3?

nevermind figured it out.  v2.0.3 fixes the issue.  Thanks!

**Comment by joelpurra** [comment]
@galak: should be easy enough! I assume you installed `uvcc` the recommended way.

```shell
# NOTE: standard global executable installation.
npm install --global uvcc

# NOTE: update global executable installation.
npm update --global uvcc
```

You can also run `npx uvcc` and always use the latest version (for this and other `npm` executables), possibly at the cost of additional network traffic/delay.

Note: haven't verified the list of controls as implemented in `uvc-control` -- thanks for this report, and please report any further issues!
